-- MySQL Script generated by MySQL Workbench
-- Tue Aug 19 21:18:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bookshop` ;

-- -----------------------------------------------------
-- Table `bookshop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  `notes` TEXT NULL DEFAULT NULL,
  `photo_path` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookshop`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`bills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_number` VARCHAR(50) NOT NULL,
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(20) NULL DEFAULT NULL,
  `bill_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `discount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `payment_status` ENUM('PAID', 'UNPAID', 'PARTIAL') NULL DEFAULT 'UNPAID',
  `payment_method` ENUM('CASH', 'CARD', 'ONLINE', 'CHEQUE') NULL DEFAULT 'CASH',
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bill_number` (`bill_number` ASC) VISIBLE,
  INDEX `idx_bill_date` (`bill_date` ASC) VISIBLE,
  INDEX `idx_payment_status` (`payment_status` ASC) VISIBLE,
  INDEX `idx_customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `bills_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bookshop`.`customers` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookshop`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(20) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `publisher` VARCHAR(100) NULL DEFAULT NULL,
  `published_date` DATE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cover_image_path` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookshop`.`bill_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`bill_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `book_title` VARCHAR(255) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_bill_id` (`bill_id` ASC) VISIBLE,
  INDEX `idx_book_id` (`book_id` ASC) VISIBLE,
  CONSTRAINT `bill_items_ibfk_1`
    FOREIGN KEY (`bill_id`)
    REFERENCES `bookshop`.`bills` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `bill_items_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookshop`.`books` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bookshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookshop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` ENUM('admin') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
